esphome:
  name: esp32-cam
  platform: ESP32

wifi:
  ssid: "Calvin"
  password: "Khongc0p@ss"
  ap:
    ssid: "ESP32-CAM Fallback"
    password: "12345678"

logger:

api:
  password: "esp32cam123"

ota:
  password: "esp32cam123"
  safe_mode: true
  reboot_timeout: 5min

web_server:
  port: 80

camera:
  - platform: esp32
    name: ESP32 Camera
    external_components:
      - source:
          type: git
          url: https://github.com/esphome/esphome
          ref: 2024.12.0
          components:
            - esp32_camera

status_led:
  pin:
    number: 33
    inverted: yes

button:
  - platform: restart
    name: "Restart ESP32-CAM"

sensor:
  - platform: wifi_signal
    name: WiFi Signal

text_sensor:
  - platform: version
    name: ESPHome Version
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
